import {
  ADMIN_CAPABILITY_CONTRACT_VERSION,
  ADMIN_CAPABILITY_IDS,
  AdminCapabilityDefinitionSchema,
  type AdminCapabilityDefinition,
  type AdminCapabilityGroupId,
} from "../types/capabilities";

export const ADMIN_CAPABILITY_GROUPS = Object.freeze([
  Object.freeze({ id: "home" as const, label: "Home", order: 0 }),
  Object.freeze({ id: "marketplace" as const, label: "Marketplace", order: 1 }),
  Object.freeze({ id: "orders_and_service" as const, label: "Orders and Service", order: 2 }),
  Object.freeze({ id: "growth" as const, label: "Growth", order: 3 }),
  Object.freeze({ id: "finance" as const, label: "Finance", order: 4 }),
  Object.freeze({ id: "governance" as const, label: "Governance", order: 5 }),
]);

type CapabilityInput = Omit<
  AdminCapabilityDefinition,
  "version" | "authorizationAuthority"
>;

function defineCapability(input: CapabilityInput): AdminCapabilityDefinition {
  const parsed = AdminCapabilityDefinitionSchema.parse({
    ...input,
    version: ADMIN_CAPABILITY_CONTRACT_VERSION,
    authorizationAuthority: "backend",
  });

  Object.freeze(parsed.frontendPermissionHints);
  Object.freeze(parsed.backendPermissionEvidence.permissions);
  Object.freeze(parsed.backendPermissionEvidence);
  Object.freeze(parsed.backendDependency);
  Object.freeze(parsed.blockers);
  return Object.freeze(parsed);
}

const registry = [
  defineCapability({
    id: "overview",
    groupId: "home",
    label: "Overview",
    purpose: "See verified marketplace activity and the work that needs attention.",
    currentRoute: "/admin/dashboard",
    routeEvidence: "The protected dashboard route renders the current backend dashboard summary.",
    frontendPermissionHints: ["view_dashboard"],
    backendPermissionEvidence: {
      state: "partial",
      permissions: ["access_admin_panel"],
      note: "The dashboard endpoint is protected, while authenticated identity does not yet expose authoritative permissions.",
    },
    completionLevel: "operational",
    navigationEligible: true,
    frontendPackage: "F2",
    backendDependency: {
      state: "available",
      owner: "backend",
      description: "Point-in-time admin dashboard summary with explicit unavailable metrics.",
    },
    evidenceNote: "The existing overview consumes one strict versioned backend summary and preserves unavailable versus zero.",
    blockers: [],
    sensitivity: "standard",
    intent: "read",
  }),
  defineCapability({
    id: "alerts_and_assigned_work",
    groupId: "home",
    label: "Alerts and Assigned Work",
    purpose: "Review alerts and work assigned to an operator or team.",
    currentRoute: null,
    routeEvidence: "No current route provides backend-owned alerts or assignments.",
    frontendPermissionHints: ["view_dashboard"],
    backendPermissionEvidence: {
      state: "missing",
      permissions: [],
      note: "Assignment, alert, and team-scoping permissions are not contracted.",
    },
    completionLevel: "contract_gated",
    navigationEligible: false,
    frontendPackage: "F1",
    backendDependency: {
      state: "missing",
      owner: "backend",
      description: "Permission-filtered alerts, assignments, teams, ownership history, and due-state authority.",
    },
    evidenceNote: "The admin architecture explicitly gates alerts, assignments, teams, and handoffs.",
    blockers: ["Backend alert and work-ownership contracts do not exist."],
    sensitivity: "sensitive",
    intent: "read_write",
  }),
  defineCapability({
    id: "analytics_and_reports",
    groupId: "home",
    label: "Analytics and Reports",
    purpose: "Review governed marketplace analysis and reports with clear definitions.",
    currentRoute: "/admin/reports",
    routeEvidence: "A protected reports route exists but remains hidden and presents an unavailable notice.",
    frontendPermissionHints: ["view_financial_reports", "export_reports"],
    backendPermissionEvidence: {
      state: "partial",
      permissions: ["view_all_reports", "view_sales_reports", "view_revenue_reports", "export_reports"],
      note: "Permission names exist, but governed report definitions, schedules, and exports are incomplete.",
    },
    completionLevel: "contract_gated",
    navigationEligible: false,
    frontendPackage: "F12",
    backendDependency: {
      state: "partial",
      owner: "backend",
      description: "Defined metrics, governed report queries, complete-result exports, and scheduling authority.",
    },
    evidenceNote: "The existing route is not evidence of an operational reporting capability.",
    blockers: ["Governed metrics, exports, and scheduled-report contracts are incomplete."],
    sensitivity: "sensitive",
    intent: "read",
  }),
  defineCapability({
    id: "sellers",
    groupId: "marketplace",
    label: "Sellers",
    purpose: "Review seller applications, evidence, status, and permitted actions.",
    currentRoute: "/admin/sellers",
    routeEvidence: "Protected seller list and review routes use real seller application services.",
    frontendPermissionHints: ["view_sellers"],
    backendPermissionEvidence: {
      state: "verified",
      permissions: ["review_sellers", "manage_seller_status"],
      note: "Backend seller review and status actions use explicit permission checks.",
    },
    completionLevel: "operational",
    navigationEligible: true,
    frontendPackage: "F3",
    backendDependency: {
      state: "available",
      owner: "backend",
      description: "Seller application collection, evidence access, review actions, and audit history.",
    },
    evidenceNote: "Current seller workflows are backend-integrated and permission-gated.",
    blockers: [],
    sensitivity: "restricted",
    intent: "read_write",
  }),
  defineCapability({
    id: "customers",
    groupId: "marketplace",
    label: "Customers",
    purpose: "Find customers and review the minimum permitted account context.",
    currentRoute: "/admin/buyers",
    routeEvidence: "The protected customer route uses the current admin user foundation.",
    frontendPermissionHints: ["view_buyers"],
    backendPermissionEvidence: {
      state: "verified",
      permissions: ["view_all_users"],
      note: "Backend user access is permission-controlled; field-level minimization remains authoritative.",
    },
    completionLevel: "operational",
    navigationEligible: true,
    frontendPackage: "F4",
    backendDependency: {
      state: "available",
      owner: "backend",
      description: "Permission-filtered customer collection and selected account operations.",
    },
    evidenceNote: "A real protected customer surface exists; future linked context remains separately gated.",
    blockers: [],
    sensitivity: "restricted",
    intent: "read_write",
  }),
  defineCapability({
    id: "products_and_moderation",
    groupId: "marketplace",
    label: "Products and Moderation",
    purpose: "Review product submissions and make reasoned moderation decisions.",
    currentRoute: "/admin/products",
    routeEvidence: "Protected product collection and detail routes use real moderation services.",
    frontendPermissionHints: ["view_products", "moderate_products"],
    backendPermissionEvidence: {
      state: "verified",
      permissions: ["view_all_products", "approve_products"],
      note: "Backend viewing and moderation actions use distinct permission evidence.",
    },
    completionLevel: "operational",
    navigationEligible: true,
    frontendPackage: "F5",
    backendDependency: {
      state: "available",
      owner: "backend",
      description: "Product collection, moderation detail, reasoned decisions, and audit evidence.",
    },
    evidenceNote: "Existing moderation is backend-integrated; reviews and inventory are separate capabilities.",
    blockers: [],
    sensitivity: "sensitive",
    intent: "read_write",
  }),
  defineCapability({
    id: "categories_and_attributes",
    groupId: "marketplace",
    label: "Categories and Attributes",
    purpose: "Manage the marketplace taxonomy and approved product attributes.",
    currentRoute: "/admin/categories",
    routeEvidence: "The protected categories route uses current category and initial attribute operations.",
    frontendPermissionHints: ["manage_content"],
    backendPermissionEvidence: {
      state: "verified",
      permissions: ["manage_categories"],
      note: "Backend category mutations remain the source of authority.",
    },
    completionLevel: "operational",
    navigationEligible: true,
    frontendPackage: "F7",
    backendDependency: {
      state: "available",
      owner: "backend",
      description: "Category tree operations and the approved initial category-attribute foundation.",
    },
    evidenceNote: "The current foundation is operational; later schema-studio depth requires its own package.",
    blockers: [],
    sensitivity: "sensitive",
    intent: "read_write",
  }),
  defineCapability({
    id: "inventory_oversight",
    groupId: "marketplace",
    label: "Inventory Oversight",
    purpose: "Review stock accuracy and inventory conditions across permitted sellers.",
    currentRoute: null,
    routeEvidence: "No dedicated inventory-oversight route or complete backend collection exists.",
    frontendPermissionHints: ["view_products"],
    backendPermissionEvidence: {
      state: "missing",
      permissions: [],
      note: "Cross-seller inventory oversight authority is not contracted.",
    },
    completionLevel: "contract_gated",
    navigationEligible: false,
    frontendPackage: "F5",
    backendDependency: {
      state: "missing",
      owner: "backend",
      description: "Server-owned stock oversight, filters, events, and permission boundaries.",
    },
    evidenceNote: "Product stock fields do not constitute an admin inventory-oversight capability.",
    blockers: ["Inventory oversight data and permissions do not exist."],
    sensitivity: "sensitive",
    intent: "read",
  }),
  defineCapability({
    id: "reviews_and_ratings",
    groupId: "marketplace",
    label: "Reviews and Ratings",
    purpose: "Moderate customer reviews and rating abuse using verified evidence.",
    currentRoute: null,
    routeEvidence: "No dedicated review-moderation route exists.",
    frontendPermissionHints: ["moderate_products"],
    backendPermissionEvidence: {
      state: "missing",
      permissions: [],
      note: "Review moderation permissions and evidence contracts are absent.",
    },
    completionLevel: "contract_gated",
    navigationEligible: false,
    frontendPackage: "F5",
    backendDependency: {
      state: "missing",
      owner: "backend",
      description: "Review collection, abuse evidence, moderation actions, and audit records.",
    },
    evidenceNote: "Ratings must remain absent where authoritative review data is unavailable.",
    blockers: ["Review moderation data, actions, and permissions do not exist."],
    sensitivity: "sensitive",
    intent: "read_write",
  }),
  defineCapability({
    id: "orders_and_fulfillment",
    groupId: "orders_and_service",
    label: "Orders and Fulfillment",
    purpose: "Review orders and perform permitted fulfillment actions against current order state.",
    currentRoute: "/admin/orders",
    routeEvidence: "The protected orders route uses real order and fulfillment services.",
    frontendPermissionHints: ["view_orders", "override_orders"],
    backendPermissionEvidence: {
      state: "verified",
      permissions: ["view_all_orders", "manage_order_fulfillment"],
      note: "Backend order viewing and fulfillment mutations are separately permission-controlled.",
    },
    completionLevel: "operational",
    navigationEligible: true,
    frontendPackage: "F6",
    backendDependency: {
      state: "available",
      owner: "backend",
      description: "Order collection, order detail, fulfillment transitions, and conflict handling.",
    },
    evidenceNote: "The current order foundation is operational; delivery and money truth remain separate.",
    blockers: [],
    sensitivity: "restricted",
    intent: "read_write",
  }),
  defineCapability({
    id: "delivery_operations",
    groupId: "orders_and_service",
    label: "Delivery Operations",
    purpose: "Coordinate delivery work, exceptions, and proof of delivery.",
    currentRoute: null,
    routeEvidence: "No dedicated delivery-operations route exists.",
    frontendPermissionHints: ["view_orders", "override_orders"],
    backendPermissionEvidence: {
      state: "missing",
      permissions: [],
      note: "Delivery-job and courier-event permissions are not contracted.",
    },
    completionLevel: "contract_gated",
    navigationEligible: false,
    frontendPackage: "F6",
    backendDependency: {
      state: "missing",
      owner: "backend",
      description: "Delivery jobs, courier events, exceptions, and proof-of-delivery authority.",
    },
    evidenceNote: "Order fulfillment status is not a substitute for a delivery-operations domain.",
    blockers: ["Delivery job, event, exception, and proof contracts do not exist."],
    sensitivity: "restricted",
    intent: "read_write",
  }),
  defineCapability({
    id: "returns_refunds_and_exchanges",
    groupId: "orders_and_service",
    label: "Returns, Refunds, and Exchanges",
    purpose: "Review remedy requests and execute approved outcomes through backend authority.",
    currentRoute: null,
    routeEvidence: "No complete returns, refunds, and exchanges route exists.",
    frontendPermissionHints: ["manage_refunds"],
    backendPermissionEvidence: {
      state: "partial",
      permissions: ["process_refunds", "issue_refunds"],
      note: "Permission vocabulary exists without the complete case, evidence, ledger, and provider contract.",
    },
    completionLevel: "contract_gated",
    navigationEligible: false,
    frontendPackage: "F10",
    backendDependency: {
      state: "missing",
      owner: "backend",
      description: "Return cases, eligibility, evidence, approval, ledger reversal, and provider outcomes.",
    },
    evidenceNote: "Refund authority cannot be inferred or executed from frontend-only state.",
    blockers: ["Case, escrow, ledger, and refund-provider contracts are incomplete."],
    sensitivity: "restricted",
    intent: "read_write",
  }),
  defineCapability({
    id: "disputes_and_claims",
    groupId: "orders_and_service",
    label: "Disputes and Claims",
    purpose: "Investigate claims, review evidence, and record authorized decisions.",
    currentRoute: "/admin/disputes",
    routeEvidence: "A protected disputes route exists but remains hidden and unavailable.",
    frontendPermissionHints: ["manage_disputes"],
    backendPermissionEvidence: {
      state: "missing",
      permissions: [],
      note: "The complete dispute-case authority and permission model is absent.",
    },
    completionLevel: "contract_gated",
    navigationEligible: false,
    frontendPackage: "F10",
    backendDependency: {
      state: "missing",
      owner: "backend",
      description: "Cases, evidence, deadlines, seller responses, decisions, and audit-safe outcomes.",
    },
    evidenceNote: "The route and foundation notice are not an operational dispute workflow.",
    blockers: ["Dispute case, evidence, decision, and financial consequence contracts do not exist."],
    sensitivity: "restricted",
    intent: "read_write",
  }),
  defineCapability({
    id: "support",
    groupId: "orders_and_service",
    label: "Support",
    purpose: "Review and respond to seller support requests with permitted context.",
    currentRoute: "/admin/support",
    routeEvidence: "The protected support route uses the existing seller support service.",
    frontendPermissionHints: ["view_support_tickets"],
    backendPermissionEvidence: {
      state: "partial",
      permissions: [],
      note: "Support endpoints exist, while authoritative permission delivery and future collaboration remain incomplete.",
    },
    completionLevel: "operational",
    navigationEligible: true,
    frontendPackage: "F8",
    backendDependency: {
      state: "available",
      owner: "backend",
      description: "Seller support ticket collection, detail, replies, and status operations.",
    },
    evidenceNote: "The current support surface is real; assignment, SLA, and internal notes remain separately gated.",
    blockers: [],
    sensitivity: "restricted",
    intent: "read_write",
  }),
  defineCapability({
    id: "risk_and_trust",
    groupId: "orders_and_service",
    label: "Risk and Trust",
    purpose: "Investigate marketplace risk signals using permission-filtered evidence.",
    currentRoute: null,
    routeEvidence: "No dedicated risk and trust route exists.",
    frontendPermissionHints: ["view_sellers", "view_orders"],
    backendPermissionEvidence: {
      state: "missing",
      permissions: [],
      note: "Risk-case permissions and evidence boundaries are not contracted.",
    },
    completionLevel: "contract_gated",
    navigationEligible: false,
    frontendPackage: "F10",
    backendDependency: {
      state: "missing",
      owner: "backend",
      description: "Risk cases, signals, evidence, decisions, ownership, and audit boundaries.",
    },
    evidenceNote: "Individual seller or order flags do not create a central risk workspace.",
    blockers: ["Risk case, signal, evidence, and permission contracts do not exist."],
    sensitivity: "restricted",
    intent: "read_write",
  }),
  defineCapability({
    id: "content_and_merchandising",
    groupId: "growth",
    label: "Content and Merchandising",
    purpose: "Manage approved marketplace content and merchandising placements.",
    currentRoute: "/admin/content",
    routeEvidence: "A protected content route exists but remains hidden and unavailable.",
    frontendPermissionHints: ["manage_content"],
    backendPermissionEvidence: {
      state: "partial",
      permissions: ["manage_content"],
      note: "A broad permission exists without governed content models and publication workflows.",
    },
    completionLevel: "contract_gated",
    navigationEligible: false,
    frontendPackage: "F11",
    backendDependency: {
      state: "missing",
      owner: "backend",
      description: "Content models, placements, review, publication state, scheduling, and audit evidence.",
    },
    evidenceNote: "The existing unavailable route must not be exposed as a live growth tool.",
    blockers: ["Governed content, placement, scheduling, and publication contracts do not exist."],
    sensitivity: "sensitive",
    intent: "read_write",
  }),
  defineCapability({
    id: "collections_and_placement",
    groupId: "growth",
    label: "Collections and Placement",
    purpose: "Curate product collections and approved discovery placements.",
    currentRoute: null,
    routeEvidence: "No collection and placement operations route exists.",
    frontendPermissionHints: ["manage_content"],
    backendPermissionEvidence: {
      state: "missing",
      permissions: [],
      note: "Collection and placement permissions are not defined.",
    },
    completionLevel: "contract_gated",
    navigationEligible: false,
    frontendPackage: "F11",
    backendDependency: {
      state: "missing",
      owner: "backend",
      description: "Collections, placement slots, eligibility, ordering, publication, and audit authority.",
    },
    evidenceNote: "Existing storefront sections are not an admin collection-management contract.",
    blockers: ["Collection, placement, publication, and permission contracts do not exist."],
    sensitivity: "sensitive",
    intent: "read_write",
  }),
  defineCapability({
    id: "promotions_and_campaigns",
    groupId: "growth",
    label: "Promotions and Campaigns",
    purpose: "Plan and govern approved marketplace promotions and campaigns.",
    currentRoute: null,
    routeEvidence: "No promotions and campaigns operations route exists.",
    frontendPermissionHints: ["manage_content"],
    backendPermissionEvidence: {
      state: "missing",
      permissions: [],
      note: "Campaign authority and eligibility permissions are not defined.",
    },
    completionLevel: "contract_gated",
    navigationEligible: false,
    frontendPackage: "F11",
    backendDependency: {
      state: "missing",
      owner: "backend",
      description: "Campaign definitions, eligibility, pricing consequences, schedules, and audit history.",
    },
    evidenceNote: "No promotion may be represented as active from frontend-only configuration.",
    blockers: ["Campaign, eligibility, pricing, and publication contracts do not exist."],
    sensitivity: "restricted",
    intent: "read_write",
  }),
  defineCapability({
    id: "customer_segments_and_price_lists",
    groupId: "growth",
    label: "Customer Segments and Price Lists",
    purpose: "Manage approved customer groups and governed price eligibility.",
    currentRoute: null,
    routeEvidence: "No customer segment or price-list operations route exists.",
    frontendPermissionHints: ["manage_content"],
    backendPermissionEvidence: {
      state: "missing",
      permissions: [],
      note: "Segment and price-list permissions are not defined.",
    },
    completionLevel: "contract_gated",
    navigationEligible: false,
    frontendPackage: "F11",
    backendDependency: {
      state: "missing",
      owner: "backend",
      description: "Segment membership, price-list rules, eligibility, checkout effects, and audit evidence.",
    },
    evidenceNote: "Customer pricing cannot be inferred or applied by the frontend.",
    blockers: ["Segment, price-list, eligibility, and checkout contracts do not exist."],
    sensitivity: "restricted",
    intent: "read_write",
  }),
  defineCapability({
    id: "search_and_discovery_operations",
    groupId: "growth",
    label: "Search and Discovery Operations",
    purpose: "Review and tune approved marketplace discovery behavior.",
    currentRoute: null,
    routeEvidence: "No search and discovery operations route exists.",
    frontendPermissionHints: ["manage_content"],
    backendPermissionEvidence: {
      state: "missing",
      permissions: [],
      note: "Discovery configuration permissions and versioned authority are absent.",
    },
    completionLevel: "contract_gated",
    navigationEligible: false,
    frontendPackage: "F11",
    backendDependency: {
      state: "missing",
      owner: "backend",
      description: "Search rules, ranking inputs, synonyms, governance, publication, and rollback.",
    },
    evidenceNote: "Consumer search behavior does not provide an admin operations contract.",
    blockers: ["Governed discovery configuration, publication, and permission contracts do not exist."],
    sensitivity: "sensitive",
    intent: "read_write",
  }),
  defineCapability({
    id: "finance_overview",
    groupId: "finance",
    label: "Finance Overview",
    purpose: "Review approved marketplace finance summaries from ledger-backed sources.",
    currentRoute: "/admin/finance",
    routeEvidence: "A protected finance route exists but remains hidden and unavailable.",
    frontendPermissionHints: ["view_treasury"],
    backendPermissionEvidence: {
      state: "partial",
      permissions: ["view_all_payouts"],
      note: "Finance-adjacent permission names exist without the required wallet, ledger, and reconciliation foundations.",
    },
    completionLevel: "contract_gated",
    navigationEligible: false,
    frontendPackage: "F10",
    backendDependency: {
      state: "missing",
      owner: "backend",
      description: "Wallet, ledger, escrow, commission, payout, refund, and reconciliation sources.",
    },
    evidenceNote: "Historic finance cards and zero values are not production finance evidence.",
    blockers: ["Wallet, ledger, escrow, payout, and reconciliation foundations are incomplete."],
    sensitivity: "restricted",
    intent: "read",
  }),
  defineCapability({
    id: "transactions_and_ledger",
    groupId: "finance",
    label: "Transactions and Ledger",
    purpose: "Inspect authorized immutable money records and their linked events.",
    currentRoute: null,
    routeEvidence: "No transaction and ledger operations route exists.",
    frontendPermissionHints: ["view_treasury"],
    backendPermissionEvidence: {
      state: "missing",
      permissions: [],
      note: "Ledger viewing and field-level permissions are not defined.",
    },
    completionLevel: "contract_gated",
    navigationEligible: false,
    frontendPackage: "F10",
    backendDependency: {
      state: "missing",
      owner: "backend",
      description: "Immutable balanced ledger entries, transaction links, masking, and audit evidence.",
    },
    evidenceNote: "No frontend-derived balance or transaction list can substitute for a ledger.",
    blockers: ["Immutable ledger, transaction, and field-permission contracts do not exist."],
    sensitivity: "restricted",
    intent: "read",
  }),
  defineCapability({
    id: "reconciliation",
    groupId: "finance",
    label: "Reconciliation",
    purpose: "Compare authorized financial records and resolve verified differences.",
    currentRoute: null,
    routeEvidence: "No reconciliation operations route exists.",
    frontendPermissionHints: ["view_treasury"],
    backendPermissionEvidence: {
      state: "missing",
      permissions: [],
      note: "Reconciliation permissions and provider evidence are not defined.",
    },
    completionLevel: "contract_gated",
    navigationEligible: false,
    frontendPackage: "F10",
    backendDependency: {
      state: "missing",
      owner: "backend",
      description: "Provider settlements, ledger comparisons, discrepancies, resolution, and audit history.",
    },
    evidenceNote: "Provider or settlement success must never be fabricated in the frontend.",
    blockers: ["Ledger, provider settlement, discrepancy, and resolution contracts do not exist."],
    sensitivity: "restricted",
    intent: "read_write",
  }),
  defineCapability({
    id: "seller_payouts",
    groupId: "finance",
    label: "Seller Payouts",
    purpose: "Review and process seller payouts only through authorized backend workflows.",
    currentRoute: null,
    routeEvidence: "No operational seller payout route exists.",
    frontendPermissionHints: ["view_treasury", "approve_payouts"],
    backendPermissionEvidence: {
      state: "partial",
      permissions: ["view_all_payouts", "process_payouts"],
      note: "Permission vocabulary exists without complete payout, escrow, ledger, and provider authority.",
    },
    completionLevel: "contract_gated",
    navigationEligible: false,
    frontendPackage: "F10",
    backendDependency: {
      state: "missing",
      owner: "backend",
      description: "Payout requests, destinations, approvals, ledger entries, provider outcomes, and holds.",
    },
    evidenceNote: "Payout success or balance cannot be controlled from frontend state.",
    blockers: ["Payout, escrow, ledger, destination, and provider contracts do not exist."],
    sensitivity: "restricted",
    intent: "read_write",
  }),
  defineCapability({
    id: "commissions",
    groupId: "finance",
    label: "Commissions",
    purpose: "Review and govern approved seller commission rules and their history.",
    currentRoute: null,
    routeEvidence: "No dedicated commission governance route exists.",
    frontendPermissionHints: ["edit_commission"],
    backendPermissionEvidence: {
      state: "missing",
      permissions: [],
      note: "Commission governance permission and versioning are not contracted.",
    },
    completionLevel: "contract_gated",
    navigationEligible: false,
    frontendPackage: "F10",
    backendDependency: {
      state: "missing",
      owner: "backend",
      description: "Versioned commission rules, effective dates, order snapshots, approval, and audit history.",
    },
    evidenceNote: "Planning percentages are not a live editable finance capability.",
    blockers: ["Versioned commission, approval, snapshot, and audit contracts do not exist."],
    sensitivity: "restricted",
    intent: "read_write",
  }),
  defineCapability({
    id: "admins_teams_and_roles",
    groupId: "governance",
    label: "Admins, Teams, and Roles",
    purpose: "Manage permitted administrator access and review current role context.",
    currentRoute: "/admin/access",
    routeEvidence: "The protected access route provides selected real administrator operations.",
    frontendPermissionHints: ["manage_admins"],
    backendPermissionEvidence: {
      state: "partial",
      permissions: ["manage_admins"],
      note: "Selected administrator operations exist; teams, durable grants, and effective-permission authority remain incomplete.",
    },
    completionLevel: "operational",
    navigationEligible: true,
    frontendPackage: "F9",
    backendDependency: {
      state: "partial",
      owner: "backend",
      description: "Selected admin-user operations now; teams, invitations, grants, sessions, and step-up later.",
    },
    evidenceNote: "Current selected operations remain live; this entry does not claim the complete future governance model.",
    blockers: [],
    sensitivity: "restricted",
    intent: "read_write",
  }),
  defineCapability({
    id: "audit_log",
    groupId: "governance",
    label: "Audit Log",
    purpose: "Review permission-filtered evidence of sensitive administrative actions.",
    currentRoute: null,
    routeEvidence: "Selected domain audit events exist, but no central audit-search route exists.",
    frontendPermissionHints: ["view_system_logs"],
    backendPermissionEvidence: {
      state: "partial",
      permissions: ["view_logs"],
      note: "Selected audit data exists without a central permission-filtered search contract.",
    },
    completionLevel: "contract_gated",
    navigationEligible: false,
    frontendPackage: "F9",
    backendDependency: {
      state: "partial",
      owner: "backend",
      description: "Central permission-filtered audit search, masking, retention, and complete event coverage.",
    },
    evidenceNote: "Domain audit summaries do not establish a central searchable audit capability.",
    blockers: ["Central audit search, masking, retention, and permission contracts are incomplete."],
    sensitivity: "restricted",
    intent: "read",
  }),
  defineCapability({
    id: "integrations_and_jobs",
    groupId: "governance",
    label: "Integrations and Jobs",
    purpose: "Review approved integration health and background work without exposing secrets.",
    currentRoute: null,
    routeEvidence: "No dedicated integration-health and jobs route exists.",
    frontendPermissionHints: ["view_system_logs"],
    backendPermissionEvidence: {
      state: "missing",
      permissions: [],
      note: "Integration-health and job-operation permissions are not contracted.",
    },
    completionLevel: "contract_gated",
    navigationEligible: false,
    frontendPackage: "F12",
    backendDependency: {
      state: "missing",
      owner: "backend",
      description: "Secret-safe integration status, job state, bounded retry authority, and audit evidence.",
    },
    evidenceNote: "Credentials and unrestricted infrastructure controls must never be exposed here.",
    blockers: ["Integration health, background job, retry, and permission contracts do not exist."],
    sensitivity: "restricted",
    intent: "read_write",
  }),
  defineCapability({
    id: "platform_settings",
    groupId: "governance",
    label: "Platform Settings",
    purpose: "Manage approved domain settings with reason, confirmation, and audit evidence.",
    currentRoute: "/admin/system",
    routeEvidence: "A protected system route exists but remains hidden and unavailable.",
    frontendPermissionHints: ["configure_platform"],
    backendPermissionEvidence: {
      state: "partial",
      permissions: ["manage_system_settings", "manage_technical_settings"],
      note: "Broad permission names exist without governed domain-setting contracts.",
    },
    completionLevel: "contract_gated",
    navigationEligible: false,
    frontendPackage: "F12",
    backendDependency: {
      state: "missing",
      owner: "backend",
      description: "Explicit domain settings, validation, versioning, step-up, audit, and rollback boundaries.",
    },
    evidenceNote: "The existing unavailable route must not become an unrestricted settings surface.",
    blockers: ["Governed setting definitions, validation, step-up, and audit contracts do not exist."],
    sensitivity: "restricted",
    intent: "read_write",
  }),
] as const;

function assertRegistryInvariants(capabilities: readonly AdminCapabilityDefinition[]): void {
  const ids = capabilities.map((capability) => capability.id);
  const routes = capabilities
    .map((capability) => capability.currentRoute)
    .filter((route): route is string => route !== null);
  const configuredGroups = new Set<AdminCapabilityGroupId>(ADMIN_CAPABILITY_GROUPS.map((group) => group.id));

  if (capabilities.length !== ADMIN_CAPABILITY_IDS.length || new Set(ids).size !== ids.length) {
    throw new Error("Admin capability registry IDs are incomplete or duplicated.");
  }
  if (ADMIN_CAPABILITY_IDS.some((id) => !ids.includes(id))) {
    throw new Error("Admin capability registry is missing a documented destination.");
  }
  if (new Set(routes).size !== routes.length) {
    throw new Error("Admin capability registry routes must be unique.");
  }
  if (capabilities.some((capability) => !configuredGroups.has(capability.groupId))) {
    throw new Error("Admin capability registry references an unknown group.");
  }
}

assertRegistryInvariants(registry);

export const ADMIN_CAPABILITY_REGISTRY: readonly AdminCapabilityDefinition[] = Object.freeze(registry);

export const ADMIN_CAPABILITY_BY_ID = Object.freeze(
  Object.fromEntries(ADMIN_CAPABILITY_REGISTRY.map((capability) => [capability.id, capability])),
) as Readonly<Record<(typeof ADMIN_CAPABILITY_IDS)[number], AdminCapabilityDefinition>>;
